spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

flyway:
  url: jdbc:h2:mem:db;INIT=CREATE SCHEMA IF NOT EXISTS artist_service_schema
  user: sa
  password: sa
  schemas: artist_service_schema

h2-server:
  port: 8081